"""fresh_initial_schema

Revision ID: 9accf4886294
Revises: 
Create Date: 2026-04-07 17:09:55.999453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9accf4886294'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('slack_workspaces',
    sa.Column('slack_workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('slack_workspace_id'),
    sa.UniqueConstraint('company_id', 'team_id', name='uq_slack_workspaces_company_team'),
    sa.UniqueConstraint('team_id', name='uq_slack_workspaces_team_id')
    )
    op.create_index('idx_slack_workspaces_company', 'slack_workspaces', ['company_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('trialing','active','past_due','canceled')", name='ck_subscriptions_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.plan_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('company_id', name='uq_subscriptions_one_per_company')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('admin','biller','viewer')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_users_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_users_company_user')
    )
    op.create_index('idx_users_company', 'users', ['company_id'], unique=False)
    op.create_table('auth_users',
    sa.Column('auth_user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('auth_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('google_mailboxes',
    sa.Column('google_mailbox_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_address', postgresql.CITEXT(), nullable=False),
    sa.Column('token_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_history_id', sa.Text(), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'user_id'], ['users.company_id', 'users.user_id'], name='fk_google_mailboxes_company_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('google_mailbox_id'),
    sa.UniqueConstraint('company_id', 'email_address', name='uq_google_mailboxes_company_email')
    )
    op.create_index('idx_google_mailboxes_company', 'google_mailboxes', ['company_id'], unique=False)
    op.create_table('message_incidents',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('slack','gmail')", name='ck_message_incidents_source'),
    sa.ForeignKeyConstraint(['company_id', 'user_id'], ['users.company_id', 'users.user_id'], name='fk_message_incidents_company_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('slack_accounts',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('slack_user_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.ForeignKeyConstraint(['company_id', 'team_id'], ['slack_workspaces.company_id', 'slack_workspaces.team_id'], name='fk_slack_accounts_company_team', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id', 'user_id'], ['users.company_id', 'users.user_id'], name='fk_slack_accounts_company_user', ondelete='RESTRICT')
    )
    op.create_index('idx_slack_accounts_company', 'slack_accounts', ['company_id'], unique=False)
    op.create_index('idx_slack_accounts_user', 'slack_accounts', ['user_id'], unique=False)
    op.create_table('incident_scores',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('neutral_score', sa.Float(), nullable=False),
    sa.Column('humor_sarcasm_score', sa.Float(), nullable=False),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('burnout_score', sa.Float(), nullable=False),
    sa.Column('depression_score', sa.Float(), nullable=False),
    sa.Column('harassment_score', sa.Float(), nullable=False),
    sa.Column('suicidal_ideation_score', sa.Float(), nullable=False),
    sa.Column('predicted_category', sa.Text(), nullable=True),
    sa.Column('predicted_severity', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message_incidents.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.drop_table('stripe_events')
    op.drop_table('payments')
    op.drop_table('stripe_subscriptions')
    op.create_unique_constraint(None, 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'incomplete'::text"), autoincrement=False, nullable=False),
    sa.Column('interval', sa.TEXT(), server_default=sa.text("'month'::text"), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['active'::text, 'past_due'::text, 'canceled'::text, 'incomplete'::text, 'trialing'::text, 'unpaid'::text])", name=op.f('ck_stripe_subscription_status')),
    sa.CheckConstraint('"interval" = ANY (ARRAY[\'month\'::text, \'year\'::text])', name=op.f('ck_stripe_subscription_interval')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('stripe_subscriptions_company_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.plan_id'], name=op.f('stripe_subscriptions_plan_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_subscriptions_pkey')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('stripe_subscriptions_stripe_subscription_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_intent_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stripe_invoice_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount_pennies', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'GBP'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['succeeded'::text, 'pending'::text, 'failed'::text, 'refunded'::text])", name=op.f('ck_payment_status')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('payments_company_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('stripe_invoice_id', name=op.f('payments_stripe_invoice_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('stripe_payment_intent_id', name=op.f('payments_stripe_payment_intent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('stripe_event_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_events_pkey')),
    sa.UniqueConstraint('stripe_event_id', name=op.f('stripe_events_stripe_event_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('incident_scores')
    op.drop_index('idx_slack_accounts_user', table_name='slack_accounts')
    op.drop_index('idx_slack_accounts_company', table_name='slack_accounts')
    op.drop_table('slack_accounts')
    op.drop_table('message_incidents')
    op.drop_index('idx_google_mailboxes_company', table_name='google_mailboxes')
    op.drop_table('google_mailboxes')
    op.drop_table('auth_users')
    op.drop_index('idx_users_company', table_name='users')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_index('idx_slack_workspaces_company', table_name='slack_workspaces')
    op.drop_table('slack_workspaces')
    # ### end Alembic commands ###
