version: '3.8'

services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.9.0
    container_name: toxiproxy
    ports:
      - "8474:8474"   # Toxiproxy API
      - "18000:18000" # Proxy → api
      - "18004:18004" # Proxy → payments
      - "19000:19000" # Proxy → webhooks
    networks:
      - sentinelai_default
    restart: unless-stopped

  toxiproxy-setup:
    image: ghcr.io/shopify/toxiproxy:2.9.0
    container_name: toxiproxy-setup
    depends_on:
      - toxiproxy
    networks:
      - sentinelai_default
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        sleep 3
        toxiproxy-cli -h toxiproxy:8474 create api_proxy --listen 0.0.0.0:18000 --upstream api:8000
        toxiproxy-cli -h toxiproxy:8474 create payments_proxy --listen 0.0.0.0:18004 --upstream payments:8001
        toxiproxy-cli -h toxiproxy:8474 create webhooks_proxy --listen 0.0.0.0:19000 --upstream webhooks:8000
        echo "Toxiproxy proxies created"
    restart: on-failure

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6:/scripts
    networks:
      - sentinelai_default
    profiles: ["load"]

  locust:
    image: locustio/locust:latest
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://api:8000
    networks:
      - sentinelai_default
    profiles: ["load"]

networks:
  sentinelai_default:
    external: true
    name: sentinelai_default