# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import slack_workspace_pb2 as slack__workspace__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in slack_workspace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SlackWorkspaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSubscriptionPlan = channel.unary_unary(
                '/sentinelai.slack.SlackWorkspaceService/CreateSubscriptionPlan',
                request_serializer=slack__workspace__pb2.CreateSubscriptionPlanRequest.SerializeToString,
                response_deserializer=slack__workspace__pb2.CreateSubscriptionPlanResponse.FromString,
                _registered_method=True)
        self.CreateCompany = channel.unary_unary(
                '/sentinelai.slack.SlackWorkspaceService/CreateCompany',
                request_serializer=slack__workspace__pb2.CreateCompanyRequest.SerializeToString,
                response_deserializer=slack__workspace__pb2.CreateCompanyResponse.FromString,
                _registered_method=True)
        self.CreateSlackWorkspace = channel.unary_unary(
                '/sentinelai.slack.SlackWorkspaceService/CreateSlackWorkspace',
                request_serializer=slack__workspace__pb2.CreateSlackWorkspaceRequest.SerializeToString,
                response_deserializer=slack__workspace__pb2.CreateSlackWorkspaceResponse.FromString,
                _registered_method=True)


class SlackWorkspaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSubscriptionPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCompany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSlackWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlackWorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSubscriptionPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSubscriptionPlan,
                    request_deserializer=slack__workspace__pb2.CreateSubscriptionPlanRequest.FromString,
                    response_serializer=slack__workspace__pb2.CreateSubscriptionPlanResponse.SerializeToString,
            ),
            'CreateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCompany,
                    request_deserializer=slack__workspace__pb2.CreateCompanyRequest.FromString,
                    response_serializer=slack__workspace__pb2.CreateCompanyResponse.SerializeToString,
            ),
            'CreateSlackWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSlackWorkspace,
                    request_deserializer=slack__workspace__pb2.CreateSlackWorkspaceRequest.FromString,
                    response_serializer=slack__workspace__pb2.CreateSlackWorkspaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinelai.slack.SlackWorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinelai.slack.SlackWorkspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SlackWorkspaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSubscriptionPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelai.slack.SlackWorkspaceService/CreateSubscriptionPlan',
            slack__workspace__pb2.CreateSubscriptionPlanRequest.SerializeToString,
            slack__workspace__pb2.CreateSubscriptionPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelai.slack.SlackWorkspaceService/CreateCompany',
            slack__workspace__pb2.CreateCompanyRequest.SerializeToString,
            slack__workspace__pb2.CreateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSlackWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinelai.slack.SlackWorkspaceService/CreateSlackWorkspace',
            slack__workspace__pb2.CreateSlackWorkspaceRequest.SerializeToString,
            slack__workspace__pb2.CreateSlackWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
