# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slack_workspace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slack_workspace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15slack_workspace.proto\x12\x10sentinelai.slack\"z\n\x10SubscriptionPlan\x12\x0f\n\x07plan_id\x18\x01 \x01(\x03\x12\x11\n\tplan_name\x18\x02 \x01(\t\x12\x19\n\x11plan_cost_pennies\x18\x03 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x15\n\rmax_employees\x18\x05 \x01(\x03\"D\n\x07\x43ompany\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12\x0f\n\x07plan_id\x18\x02 \x01(\x03\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\"A\n\x0eSlackWorkspace\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\ncompany_id\x18\x02 \x01(\x03\x12\x0f\n\x07team_id\x18\x03 \x01(\t\"q\n\x1d\x43reateSubscriptionPlanRequest\x12\x11\n\tplan_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ost_pennies\x18\x02 \x01(\x03\x12\x15\n\rmax_employees\x18\x03 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\"R\n\x1e\x43reateSubscriptionPlanResponse\x12\x30\n\x04plan\x18\x01 \x01(\x0b\x32\".sentinelai.slack.SubscriptionPlan\"=\n\x14\x43reateCompanyRequest\x12\x0f\n\x07plan_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\"C\n\x15\x43reateCompanyResponse\x12*\n\x07\x63ompany\x18\x01 \x01(\x0b\x32\x19.sentinelai.slack.Company\"X\n\x1b\x43reateSlackWorkspaceRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\x03\x12\x0f\n\x07team_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\"S\n\x1c\x43reateSlackWorkspaceResponse\x12\x33\n\tworkspace\x18\x01 \x01(\x0b\x32 .sentinelai.slack.SlackWorkspace2\xed\x02\n\x15SlackWorkspaceService\x12{\n\x16\x43reateSubscriptionPlan\x12/.sentinelai.slack.CreateSubscriptionPlanRequest\x1a\x30.sentinelai.slack.CreateSubscriptionPlanResponse\x12`\n\rCreateCompany\x12&.sentinelai.slack.CreateCompanyRequest\x1a\'.sentinelai.slack.CreateCompanyResponse\x12u\n\x14\x43reateSlackWorkspace\x12-.sentinelai.slack.CreateSlackWorkspaceRequest\x1a..sentinelai.slack.CreateSlackWorkspaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slack_workspace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIPTIONPLAN']._serialized_start=43
  _globals['_SUBSCRIPTIONPLAN']._serialized_end=165
  _globals['_COMPANY']._serialized_start=167
  _globals['_COMPANY']._serialized_end=235
  _globals['_SLACKWORKSPACE']._serialized_start=237
  _globals['_SLACKWORKSPACE']._serialized_end=302
  _globals['_CREATESUBSCRIPTIONPLANREQUEST']._serialized_start=304
  _globals['_CREATESUBSCRIPTIONPLANREQUEST']._serialized_end=417
  _globals['_CREATESUBSCRIPTIONPLANRESPONSE']._serialized_start=419
  _globals['_CREATESUBSCRIPTIONPLANRESPONSE']._serialized_end=501
  _globals['_CREATECOMPANYREQUEST']._serialized_start=503
  _globals['_CREATECOMPANYREQUEST']._serialized_end=564
  _globals['_CREATECOMPANYRESPONSE']._serialized_start=566
  _globals['_CREATECOMPANYRESPONSE']._serialized_end=633
  _globals['_CREATESLACKWORKSPACEREQUEST']._serialized_start=635
  _globals['_CREATESLACKWORKSPACEREQUEST']._serialized_end=723
  _globals['_CREATESLACKWORKSPACERESPONSE']._serialized_start=725
  _globals['_CREATESLACKWORKSPACERESPONSE']._serialized_end=808
  _globals['_SLACKWORKSPACESERVICE']._serialized_start=811
  _globals['_SLACKWORKSPACESERVICE']._serialized_end=1176
# @@protoc_insertion_point(module_scope)
